-- =====================================================================
-- Sample data for the storefront-facing tables: food_categories,
-- products, catering_packages, package_items.
--
-- Run this in the Supabase SQL editor (the postgres role bypasses RLS).
--
-- NOT included here: profiles, carts, orders, reservations, staff_tasks,
-- payments. Those either require a real auth.users row (created by
-- signing up through the app) or are generated by using the app itself.
--
-- Safe to re-run: each block only inserts rows that don't already exist
-- (matched by name), so running this twice won't duplicate data.
-- =====================================================================

-- ---------------------------------------------------------------------
-- food_categories
-- ---------------------------------------------------------------------
insert into public.food_categories (category_name, description)
select v.category_name, v.description
from (values
  ('Nuts & Seeds', 'Roasted and raw nuts, seeds, and trail mixes'),
  ('Dried Fruits', 'Naturally dried and preserved fruits'),
  ('Dried Meat & Jerky', 'Air-dried and smoked meat snacks'),
  ('Grains & Rice', 'Dried grains, rice, and legumes'),
  ('Spices & Herbs', 'Dried spices, herbs, and seasoning blends'),
  ('Snack Mixes', 'Ready-to-eat dried snack combinations')
) as v(category_name, description)
where not exists (
  select 1 from public.food_categories fc where fc.category_name = v.category_name
);

-- ---------------------------------------------------------------------
-- products
-- ---------------------------------------------------------------------
insert into public.products (category_id, product_name, description, price, unit, stock_quantity, is_active)
select c.id, v.product_name, v.description, v.price, v.unit, v.stock_quantity, true
from (values
  ('Nuts & Seeds', 'Roasted Almonds', 'Lightly salted roasted almonds', 3500.00, 'kg', 120),
  ('Nuts & Seeds', 'Raw Cashews', 'Premium whole raw cashews', 5500.00, 'kg', 80),
  ('Nuts & Seeds', 'Pumpkin Seeds', 'Hulled and roasted pumpkin seeds', 2800.00, 'kg', 60),
  ('Nuts & Seeds', 'Mixed Nuts', 'Almonds, cashews, walnuts, and pistachios', 4800.00, 'kg', 45),
  ('Dried Fruits', 'Dried Mango Slices', 'Sun-dried mango, no added sugar', 3200.00, 'kg', 70),
  ('Dried Fruits', 'Raisins', 'Sweet seedless raisins', 1900.00, 'kg', 150),
  ('Dried Fruits', 'Dried Apricots', 'Soft dried apricots', 3600.00, 'kg', 55),
  ('Dried Fruits', 'Banana Chips', 'Crispy fried banana chips, lightly sweetened', 1400.00, 'kg', 90),
  ('Dried Meat & Jerky', 'Beef Jerky', 'Classic marinated beef jerky', 7500.00, 'kg', 30),
  ('Dried Meat & Jerky', 'Spicy Chicken Jerky', 'Chili-lime marinated chicken jerky', 6800.00, 'kg', 25),
  ('Dried Meat & Jerky', 'Dried Fish Flakes', 'Traditional smoked and dried fish', 4200.00, 'kg', 20),
  ('Grains & Rice', 'Jasmine Rice', 'Premium long-grain jasmine rice', 420.00, 'kg', 300),
  ('Grains & Rice', 'Red Lentils', 'Split red lentils', 650.00, 'kg', 200),
  ('Grains & Rice', 'Rolled Oats', 'Whole grain rolled oats', 900.00, 'kg', 180),
  ('Spices & Herbs', 'Dried Basil', 'Aromatic dried basil leaves', 480.00, '100g', 100),
  ('Spices & Herbs', 'Chili Flakes', 'Crushed dried red chili', 350.00, '100g', 110),
  ('Spices & Herbs', 'Bay Leaves', 'Whole dried bay leaves', 300.00, '100g', 90),
  ('Snack Mixes', 'Tropical Trail Mix', 'Dried mango, banana chips, cashews, coconut', 3200.00, 'kg', 65),
  ('Snack Mixes', 'Protein Power Mix', 'Almonds, pumpkin seeds, dried cranberries', 4200.00, 'kg', 50),
  ('Snack Mixes', 'Classic Trail Mix', 'Raisins, peanuts, sunflower seeds', 2400.00, 'kg', 75)
) as v(category_name, product_name, description, price, unit, stock_quantity)
join public.food_categories c on c.category_name = v.category_name
where not exists (
  select 1 from public.products p where p.product_name = v.product_name
);

-- ---------------------------------------------------------------------
-- catering_packages
-- ---------------------------------------------------------------------
insert into public.catering_packages (package_name, description, price, minimum_people, maximum_people, is_active)
select v.package_name, v.description, v.price, v.minimum_people, v.maximum_people, true
from (values
  ('Basic Gathering', 'Simple finger food and snack platters for small get-togethers', 75000.00, 10, 25),
  ('Standard Celebration', 'Full snack and dessert spread with dried fruit and nut displays', 165000.00, 25, 60),
  ('Premium Event', 'Elevated presentation with jerky boards, trail mix bars, and custom platters', 360000.00, 50, 120),
  ('Corporate Package', 'Office-friendly snack boxes and coffee-break spreads', 240000.00, 20, 100),
  ('Wedding Package', 'Full-service dried food dessert and favor stations', 750000.00, 80, 250)
) as v(package_name, description, price, minimum_people, maximum_people)
where not exists (
  select 1 from public.catering_packages cp where cp.package_name = v.package_name
);

-- ---------------------------------------------------------------------
-- package_items (free-text item names per package)
-- ---------------------------------------------------------------------
insert into public.package_items (package_id, item_name, quantity, notes)
select pkg.id, v.item_name, v.quantity, v.notes
from (values
  ('Basic Gathering', 'Mixed nut platters', 2, null),
  ('Basic Gathering', 'Classic trail mix bowls', 2, null),
  ('Basic Gathering', 'Dried mango platter', 1, null),

  ('Standard Celebration', 'Mixed nut platters', 4, null),
  ('Standard Celebration', 'Tropical trail mix bowls', 3, null),
  ('Standard Celebration', 'Dried apricot & fruit board', 2, null),
  ('Standard Celebration', 'Banana chip baskets', 2, null),

  ('Premium Event', 'Beef jerky charcuterie boards', 4, 'premium cut'),
  ('Premium Event', 'Spicy chicken jerky platters', 3, null),
  ('Premium Event', 'Protein power mix bar', 5, 'self-serve station'),
  ('Premium Event', 'Cashew & nut displays', 3, null),
  ('Premium Event', 'Dried mango dessert boards', 3, null),

  ('Corporate Package', 'Roasted almond snack boxes', 3, 'individually packed'),
  ('Corporate Package', 'Classic trail mix boxes', 4, 'individually packed'),
  ('Corporate Package', 'Raisin & fruit cups', 2, null),

  ('Wedding Package', 'Protein power mix favor bags', 8, 'guest favors'),
  ('Wedding Package', 'Tropical trail mix stations', 8, null),
  ('Wedding Package', 'Dried apricot dessert boards', 5, null),
  ('Wedding Package', 'Beef jerky grazing tables', 5, null),
  ('Wedding Package', 'Mixed nut displays', 6, null)
) as v(package_name, item_name, quantity, notes)
join public.catering_packages pkg on pkg.package_name = v.package_name
where not exists (
  select 1 from public.package_items pi
  where pi.package_id = pkg.id and pi.item_name = v.item_name
);
