import { useEffect, useState } from 'react'
import toast from 'react-hot-toast'
import { supabase } from '../../lib/supabaseClient'
import { useAuth } from '../../contexts/AuthContext'
import { uploadReportFile } from '../../lib/storage'
import DataTable from '../../components/common/DataTable'
import { Button, PageHeader } from '../../components/common/FormControls'

export default function ReportsAdmin() {
  const { user } = useAuth()
  const [reports, setReports] = useState([])
  const [loading, setLoading] = useState(true)
  const [generating, setGenerating] = useState(false)

  const load = async () => {
    setLoading(true)
    const { data, error } = await supabase
      .from('reports')
      .select('*, generated_by_profile:profiles(full_name)')
      .order('generated_at', { ascending: false })
    if (error) console.error('Failed to load reports', error)
    setReports(data ?? [])
    setLoading(false)
  }

  useEffect(() => {
    load()
  }, [])

  const handleGenerate = async () => {
    setGenerating(true)
    try {
      const { data: orders, error: ordersError } = await supabase
        .from('product_orders')
        .select('id, created_at, total_amount, status, payment_status')
      if (ordersError) throw ordersError

      const rows = [
        ['Order ID', 'Date', 'Total', 'Status', 'Payment Status'],
        ...orders.map((o) => [o.id, o.created_at, o.total_amount, o.status, o.payment_status]),
      ]
      const csv = rows.map((r) => r.join(',')).join('\n')
      const filename = `sales-summary-${new Date().toISOString().slice(0, 10)}.csv`
      const fileUrl = await uploadReportFile(csv, filename)

      const { error: insertError } = await supabase.from('reports').insert({
        report_name: filename,
        generated_by: user.id,
        file_url: fileUrl,
      })
      if (insertError) throw insertError

      toast.success('Report generated')
      load()
    } catch (err) {
      console.error(err)
      toast.error(err.message || 'Could not generate report')
    } finally {
      setGenerating(false)
    }
  }

  return (
    <div>
      <PageHeader
        title="Reports"
        description="Generate and download sales reports"
        actions={<Button onClick={handleGenerate} disabled={generating}>{generating ? 'Generating...' : 'Generate sales report'}</Button>}
      />
      <DataTable
        loading={loading}
        data={reports}
        emptyMessage="No reports generated yet"
        columns={[
          { key: 'report_name', header: 'Report' },
          { key: 'generated_by_profile', header: 'Generated by', render: (row) => row.generated_by_profile?.full_name || '-' },
          { key: 'generated_at', header: 'Date', render: (row) => new Date(row.generated_at).toLocaleString() },
          {
            key: 'file_url',
            header: '',
            render: (row) => row.file_url ? <a href={row.file_url} target="_blank" rel="noreferrer" className="text-primary-600 hover:underline">Download</a> : '-',
          },
        ]}
      />
    </div>
  )
}
